"use client";

import { useEffect, useState } from "react";

function useCountUp(target, duration = 2000) {
  const [count, setCount] = useState(0);

  useEffect(() => {
    let start = 0;
    const increment = target / (duration / 16);
    const timer = setInterval(() => {
      start += increment;
      if (start >= target) {
        setCount(target);
        clearInterval(timer);
      } else {
        setCount(Math.floor(start));
      }
    }, 16);
    return () => clearInterval(timer);
  }, [target, duration]);

  return count;
}

export default function AnimatedStats() {
  const income = useCountUp(60000000);
  const students = useCountUp(230);
  const days = useCountUp(30);

  return (
    <div className="text-black space-y-8 text-left">
      <div className="border-l-4 border-[#2814de] pl-5">
        <p className="text-3xl md:text-4xl font-extrabold text-[#ef4444]">
          ${income.toLocaleString()}
        </p>
        <p className="text-gray-500 mt-1">
          in combined annual income generated by students
        </p>
      </div>

      <div className="border-l-4 border-[#2814de] pl-5">
        <p className="text-3xl md:text-4xl font-extrabold text-[#ef4444]">
          {students}+
        </p>
        <p className="text-gray-500 mt-1">
          students empowered with AI
        </p>
      </div>

      <div className="border-l-4 border-[#2814de] pl-5">
        <p className="text-3xl md:text-4xl font-extrabold text-[#ef4444]">
          {days} Days
        </p>
        <p className="text-gray-500 mt-1">
          average time to first result
        </p>
      </div>
    </div>
  );
}